### PR TITLE
Issue #35 - Added simple note for your current task.

### PR DESCRIPTION
**Pull request by plopp**
I implemented a small note/tag for each session:
skarmklipp 2017-04-18 20 59 12

A window pops up when the session is finished:
skarmklipp 2017-04-18 20 59 04

This can be turned on or off via the preferences. The tag is visible in the session list and is also exported as expected:
skarmklipp 2017-04-18 20 59 24

This should solve issue #35.

### CODE REVIEW

**Comment by priyaleo** [comment]
I'm eagerly waiting for this feature to be integrated in the app

**Comment by plopp** [comment]
@joaomoreno Hi! Will this ever get pulled or should I close it?

Regards,

**Comment by joaomoreno** [comment]
@plopp Sorry for not replying. I haven't maintained Thyme in a long _thyme_. Saving this for a slow weekend. Please don't close it.

**Comment by ken-experiment** [comment]
@joaomoreno I would really you merging this PR and making this feature available.

Thanks for both of your contributions @plopp @joaomoreno

**Comment by Misko07** [comment]
@plopp this is a great addition, thanks!! Is it possible to pull this on my side?

**Comment by cynergist** [comment]
@joaomoreno I really like Thyme and want to recommend it for a group I work with to help keep track of their pro bono legal work. The PR from @plopp would be really useful for them. Thank you for your contribution here.

**Comment by tolribeiro** [comment]
I was just about to start doing this when I saw this thread. @joaomoreno I love the app and with this addition it would be perfect!

**Comment by plopp** [comment]
@Misko07 Sure you can! Until @joaomoreno merges my PR, just clone [my repo](https://github.com/plopp/thyme) and build it with xcode. Good luck!

**Comment by joaomoreno** [comment]
Sorry guys, Thyme is just not in my radar any more. I'm looking for someone to take over the project. Let me know if any of you would like to take it.

**Comment by tolribeiro** [comment]
Maybe @plopp could be take over as a header and I'd support it along with him. How does that sound? 😬

**Comment by plopp** [comment]
@joaomoreno @tolribeiro Sure! We can try that. I’m not sure how much effort I can put into it though, but fixing a few issues and merging PR:s should be no problem.

**Comment by joaomoreno** [comment]
@plopp @tolribeiro I've added you both as collaborators, feel free to start pushing! Let's see how far we get. :+1:

**Pull request merged**
